mrd_parameters:
  condition_patho: Pathologique
  condition_sain: Sain
  eln_standards:
    clinical_positivity_pct: 0.1
    min_cluster_events: 50
  enabled: true
  method: jf
  method_flo:
    normal_marrow_multiplier: 2.0
  method_jf:
    max_normal_marrow_pct: 0.1
    min_patho_cells_pct: 10.0
